version: "3.9"
services:
  postgres:
    image: postgres:13.3
    expose:
      - 5432
    ports:
      - 5436:5432
    environment:
      POSTGRES_DB: "notes_db"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "1234"
  notes_app: 
    image: tz-kode:latest
    ports:
      - 8080:8080