// Code generated by mockery v2.28.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NoteCreator is an autogenerated mock type for the NoteCreator type
type NoteCreator struct {
	mock.Mock
}

// CreateNote provides a mock function with given fields: title, text, userId
func (_m *NoteCreator) CreateNote(title string, text string, userId string) (string, error) {
	ret := _m.Called(title, text, userId)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string) (string, error)); ok {
		return rf(title, text, userId)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) string); ok {
		r0 = rf(title, text, userId)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(title, text, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewNoteCreator interface {
	mock.TestingT
	Cleanup(func())
}

// NewNoteCreator creates a new instance of NoteCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNoteCreator(t mockConstructorTestingTNewNoteCreator) *NoteCreator {
	mock := &NoteCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
